//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCHCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSchedule
    {
        public int Id { get; set; }
        public long DoctorId { get; set; }
        public string Day { get; set; }
        public string TimeTo { get; set; }
        public string TimeFrom { get; set; }
    
        public virtual User User { get; set; }
    }
}
